### ISSUE TITLE
Kann Anzeigen nicht hochladen

### ISSUE THREAD

**Issue by Cabin-fever** [gastonx/AnzeigenChef-Windows#3]
Hallo Chef,

die Idee Deiner Frau hätte von mir kommen können und ich bin daher auch mindestens so ein großer Fan von der Umsetzung wie sie selbst. Leider habe ich keinen Mac und so bin ich auf die Windows Version angewiesen.

Einloggen funktioniert, Kategorien werden auch offenbar synchronisiert, sind jedenfalls zur Auswahl verfügbar. Allerdings kann ich keine Anzeigen hochladen - es funktioniert nur das Anlegen von Vorlagen. Egal wo ich den Cursor positioniere (ob unter Vorlagen oder z.B. unter Aktiv) - es ist nicht möglich, "Hochladen" anzuklicken, es ist immer ausgegraut. Screenshot anbei.

Viele Grüße
Jörg
![bild 001](https://cloud.githubusercontent.com/assets/13592567/9015702/f9a2436e-37ca-11e5-859e-9099b6270c3c.png)

**Comment by gastonx** [comment]
Hallo, 

das ist richtig. Das hochladen ist noch nicht fertig aber es geht im Moment sehr schnell voran. Mal schauen, ob ich es noch zum Wochenende fertig bekomme :)

**Comment by Cabin-fever** [comment]
Hallo Chef, 
das funktioniert mittlerweile. Erst gingen Fotos noch nicht mit, aber auch das klappt heute. Herzlichen Dank!
Viele Grüße
Jörg
